apiVersion: v2
name: release-operator
description: Helm chart for release-operator.
home: https://github.com/giantswarm/release-operator
version: '[[ .Version ]]'
appVersion: '[[ .AppVersion ]]'
annotations:
  io.giantswarm.application.team: honeybadger
